# Generated by Django 5.0.14 on 2025-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
